[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-apps-macros"
repository = "https://github.com/appaquet/exocore"
version = "0.1.3"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
futures = "0.3"
log = "0.4"
quote = "1.0"
syn = {version = "1.0", features = ["full", "fold"]}
thiserror = "1.0"
