[package]
name = "exocore-client-android"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
exocore-common = { path = "../../common" }
exocore-transport = { path = "../../transport", features = ["libp2p_transport"] }
exocore-index = { path = "../../index" }
failure = "0.1"
