[package]
name = "exocore-client-web"
version = "0.1.3"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
exocore-protos = { version = "0.1.3", path = "../../protos", default-features = false  }
exocore-core = { version = "0.1.3", path = "../../core", default-features = false  }
exocore-store = { version = "0.1.3", path = "../../store", default-features = false, features = ["remote"] }
exocore-transport = { version = "0.1.3", path = "../../transport", default-features = false, features = ["p2p-web"]  }
exocore-discovery = { version = "0.1.3", path = "../../discovery", default-features = false  }
thiserror = "1.0"
anyhow = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] } # serde for serialization from JsValue
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Storage"] }
log = "0.4"
wasm-logger = "0.2"
futures = "0.3"

# Needed to force rand 0.7 to load with wasm support
# TODO: Remove once https://github.com/libp2p/rust-libp2p/pull/1899 is merged
rand07 = { package = "rand", version = "0.7", features = ["wasm-bindgen"] }

# Temporary until https://github.com/rustwasm/wasm-pack/issues/886 is fixed
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-mutable-globals"]