[package]
name = "exocore-store"
description = "Store layer of Exocore (Distributed applications framework)"
version = "0.1.2"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["local"]
local = ["tantivy", "exocore-chain/engine", "crc", "lru"]
tests-utils = []

[dependencies]
exocore-chain = { version = "0.1.2", path = "../chain", default-features = false }
exocore-transport = {version = "0.1.2",  path = "../transport", default-features = false }
exocore-core = { version = "0.1.2", path = "../core" }
thiserror = "1.0"
anyhow = "1.0"
itertools = "0.10"
log = "0.4"
futures = "0.3"
prost = "0.7"
bytes = "1.0"
chrono = { version = "0.4", features = ["serde"] }
smallvec = "1.6"

# Local store
tantivy = { version = "0.13", optional = true }
crc = { version = "1.8", optional = true }
lru = { version = "0.6", optional = true }

[dev-dependencies]
tempfile = "3.2"
exocore-chain = { version = "0.1.2", path = "../chain", features = ["tests-utils"] }
exocore-core = { version = "0.1.2", path = "../core", features = ["tests-utils"] }
tokio = { version = "0.3", features = ["macros"], default-features = false }
