[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Protobuf and cap'n protos of Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-protos"
repository = "https://github.com/appaquet/exocore"
version = "0.1.24"

[dependencies]
anyhow = "1.0.68"
base64 = "0.21"
capnp = { version = "0.16", features = ["sync_reader"] }
chrono = "0.4.23"
prost = "0.11.6"
prost-types = "0.11.6"
protobuf = "3.2.0"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.92"
thiserror = "1.0.38"

[build-dependencies]
capnpc = "0.16"
prost-build = "0.11.6"
