[package]
name = "exocore-core"
description = "Core of Exocore (Distributed applications framework)"
version = "0.1.2"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
tests-utils = ["runtime", "logger"]
runtime = [
    "tokio/io-util",
    "tokio/io-std",
    "tokio/net",
    "tokio/stream",
    "tokio/rt",
    "tokio/rt-multi-thread",
    "tokio/sync",
    "tokio/time",
    "tokio/macros"
]
logger = ["log4rs"]

[dependencies]
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
multihash = "0.13"
bs58 = "0.4"
capnp = { version = "0.14", features = ["sync_reader"] }
byteorder = "1.3"
thiserror = "1.0"
anyhow = "1.0"
libp2p = { version = "0.33", features = ["noise"], default-features = false }
chrono = "0.4"
wasm-timer = "0.2"
futures = { version = "0.3", features = ["async-await"] }
protobuf = "2"
prost = "0.7"
prost-types = "0.7"
bytes = "1.0"
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }
petname = "1.0"
rand = "0.8"
url = "2.2"
base64 = "0.13"

# logger
log4rs = { version = "1.0", optional = true }

[target."cfg(target_arch = \"wasm32\")".dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
getrandom = { version = "0.2", features = ["js"] } # see https://docs.rs/getrandom/0.2.0/getrandom/#webassembly-support
parking_lot = { version = "0.11", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "0.3", features = ["rt"], default-features = false }

[build-dependencies]
capnpc = "0.14"
prost-build = "0.7"

[dev-dependencies]
tempfile = "3.1"
log4rs = "1.0"
criterion_bencher_compat = "0.3"

[[bench]]
name = "capnp_frame"
harness = false
