[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Core of Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-core"
repository = "https://github.com/appaquet/exocore"
version = "0.1.18"

[features]
logger = ["log4rs"]
runtime = [
  "tokio/io-util",
  "tokio/io-std",
  "tokio/net",
  "tokio/rt",
  "tokio/rt-multi-thread",
  "tokio/sync",
  "tokio/time",
  "tokio/macros",
]
tests-utils = ["runtime", "logger"]
web = [
  "getrandom/js", # see https://docs.rs/getrandom/0.2.0/getrandom/#webassembly-support  
  "web-sys",
]

[dependencies]
anyhow = "1.0"
bs58 = "0.4"
byteorder = "1.4"
bytes = "1.1"
chrono = "0.4"
exocore-protos = {version = "0.1.18", path = "../protos"}
futures = {version = "0.3", features = ["async-await"]}
libp2p = {version = "=0.41.1", features = ["noise", "secp256k1"], default-features = false}
log = "0.4"
log4rs = {version = "1.0", optional = true}
multihash = "0.16"
petname = "1.1"
rand = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
shadow-rs = {version = "0.8", default-features = false}
thiserror = "1.0"
url = "2.2"
uuid = {version = "0.8", features = ["v4", "wasm-bindgen"]}
wasm-timer = "0.2"

# web
web-sys = {version = "0.3", features = ["Storage"], optional = true}

[target."cfg(target_arch = \"wasm32\")".dependencies]
getrandom = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = {version = "1.16", features = ["rt"], default-features = false}

[build-dependencies]
shadow-rs = {version = "0.8", default-features = false}

[dev-dependencies]
criterion_bencher_compat = "0.3"
log4rs = "1.0"
tempfile = "3.2"
tokio = {version = "1.16", features = ["macros", "rt", "rt-multi-thread", "time"], default-features = false}

[[bench]]
harness = false
name = "capnp_frame"
