[package]
name = "exocore-core"
description = "Core of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[features]
tests_utils = ["log4rs", "runtime"]
runtime = ["tokio/full"]

[dependencies]
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
parity-multihash = "0.2"
sha3 = "0.8"
bs58 = "0.3"
capnp = { version = "=0.10.3", git = "https://github.com/appaquet/capnproto-rust.git", branch = "thread-safe-arena-readlimiter" }
byteorder = "1.3"
failure = "0.1"
libp2p-core = "0.16"
chrono = "0.4"
wasm-timer = "0.2"
futures = { version = "0.3", features = ["async-await", "compat"] }
tokio = { version = "0.2", features = ["rt-core", "blocking"], default-features = false }
protobuf = "2"
prost = "0.6"
prost-types = "0.6"
bytes = "0.5"
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }

# tests_utils
log4rs = { version = "0.11", optional = true }

[target."cfg(all(target_arch = \"wasm32\", target_os = \"unknown\"))".dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] } # serde for serialization from JsValue
wasm-bindgen-futures = "0.4"

[build-dependencies]
capnpc = { version = "=0.10.1", git = "https://github.com/appaquet/capnproto-rust.git", branch = "thread-safe-arena-readlimiter" }
prost-build = "0.6"

[dev-dependencies]
tempdir = "0.3"
log4rs = "0.11"
criterion_bencher_compat = "0.3"

[[bench]]
name = "capnp_frame"
harness = false
