[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Core of Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-core"
repository = "https://github.com/appaquet/exocore"
version = "0.1.23"

[features]
logger = ["log4rs"]
runtime = [
  "tokio/io-util",
  "tokio/io-std",
  "tokio/net",
  "tokio/rt",
  "tokio/rt-multi-thread",
  "tokio/sync",
  "tokio/time",
  "tokio/macros",
]
tests-utils = ["runtime", "logger"]
web = [
  "getrandom/js", # see https://docs.rs/getrandom/0.2.0/getrandom/#webassembly-support  
  "web-sys",
]

[dependencies]
anyhow = "1.0.60"
bs58 = "0.4.0"
byteorder = "1.4.3"
bytes = "1.2.1"
chrono = "0.4.22"
exocore-protos = {version = "0.1.23", path = "../protos"}
futures = { version = "0.3.21", features = ["async-await"] }
libp2p = { version = "0.46.1", features = ["noise", "secp256k1"], default-features = false }
log = "0.4.17"
log4rs = { version = "1.1.1", optional = true }
multihash = "0.16.3"
petname = "1.1.2"
rand = "0.8"
serde = "1.0.143"
serde_derive = "1.0.142"
serde_json = "1.0.83"
serde_yaml = "0.9.4"
shadow-rs = { version = "0.16.2", default-features = false }
thiserror = "1.0.32"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4", "wasm-bindgen"] }
wasm-timer = "0.2.5"

# web
web-sys = { version = "0.3.59", features = ["Storage"], optional = true }

[target."cfg(target_arch = \"wasm32\")".dependencies]
getrandom = "0.2.7"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
chrono = { version = "0.4.22", default-features = false, features = [] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.20.1", features = ["rt"], default-features = false }

[build-dependencies]
shadow-rs = { version = "0.16.2", default-features = false }

[dev-dependencies]
criterion_bencher_compat = "0.3.4"
log4rs = "1.1.1"
tempfile = "3.3.0"
tokio = { version = "1.20.1", features = ["macros", "rt", "rt-multi-thread", "time"], default-features = false }

[[bench]]
harness = false
name = "capnp_frame"
