[package]
name = "exocore-transport"
description = "Transport layer of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[features]
default = ["libp2p_transport"]
tests_utils = ["exocore-core/tests_utils"]
libp2p_transport = ["libp2p"]
libp2p_wasm = ["libp2p/wasm-ext", "libp2p-wasm-ext"]

[dependencies]
exocore-core = { path = "../core" }
log = "0.4"
failure = "0.1"
futures = { version = "0.3", features = ["compat"] }
pin-project = "0.4"
byteorder = "1.3"

# libp2p_transport
libp2p = { version = "0.17", optional = true, default-features = false, features = [ "dns", "mplex", "secio", "tcp", "wasm-ext", "websocket", "yamux" ] }
libp2p-wasm-ext = { version = "0.17", features = ["websocket"], optional = true }

[dev-dependencies]
exocore-core = { path = "../core", features = ["tests_utils"] }
