[package]
name = "exocore-transport"
description = "Transport layer of Exocore (Distributed applications framework)"
version = "0.1.3"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["p2p-full", "http-server"]
tests-utils = ["exocore-core/tests-utils"]
p2p-web = ["p2p-base", "libp2p/wasm-ext-websocket"] 
p2p-full = ["p2p-base", "libp2p/tcp-tokio"]
p2p-base = ["libp2p"]
http-server = ["hyper", "url"]

[dependencies]
exocore-protos = { version = "0.1.3", path = "../protos" }
exocore-core = { version = "0.1.3", path = "../core" }
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
pin-project = "1.0"
byteorder = "1.3"
libp2p = { version = "0.34", optional = true, default-features = false, features = [ "dns", "mplex", "noise", "websocket", "yamux", "ping", "identify" ] }
hyper = { version = "0.14", features = ["full"], optional = true }
url = { version = "2.2", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
exocore-core = { version = "0.1.3", path = "../core", features = ["tests-utils"] }
tokio = { version = "1.1", features = ["macros"], default-features = false }
