[package]
name = "exocore-transport"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[features]
tests_utils = ["exocore-common/tests_utils", "tokio/rt-full"]
websocket_transport = ["websocket", "tokio/reactor"]
libp2p_transport = ["libp2p", "tokio/timer"]

[dependencies]
exocore-common = { path = "../common" }
log = "0.4"
failure = "0.1"
tokio = { version = "0.1", features = ["io"], default-features = false }
futures = { version = "0.3", features = ["async-await", "compat"] }
futures01 = { package = "futures", version = "0.1" }

# Websocket transport
websocket = { version = "0.24", optional = true, default-features = false, features = ["async"] }

# libp2p transport
libp2p = { version = "0.13", features = ["secp256k1"], default-features = false, optional = true }

[dev-dependencies]
exocore-common = { path = "../common", features = ["tests_utils"] }
