[package]
name = "exocore-transport"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[features]
default = ["libp2p_transport"]
tests_utils = ["exocore-common/tests_utils", "tokio/rt-full"]
websocket_transport = ["websocket", "tokio/reactor"]
libp2p_transport = ["libp2p-core", "libp2p-swarm", "libp2p-tcp", "libp2p-dns", "libp2p-yamux", "libp2p-mplex", "libp2p-secio", "tokio/timer"]

[dependencies]
exocore-common = { path = "../common" }
futures = "0.1"
log = "0.4"
failure = "0.1"
tokio = { version = "0.1", features = ["io"], default-features = false }

# Websocket transport
websocket = { version = "0.23", optional = true }

# libp2p transport
libp2p-core = { version = "0.11", optional = true }
libp2p-swarm = { version = "0.1.0", optional = true }
libp2p-tcp = { version = "0.11", optional = true }
libp2p-dns = { version = "0.11", optional = true }
libp2p-yamux = { version = "0.11", optional = true }
libp2p-mplex = { version = "0.11", optional = true }
libp2p-secio = { version = "0.11", optional = true }

[dev-dependencies]
exocore-common = { path = "../common", features = ["tests_utils"] }
