[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "CLI for Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exo"
repository = "https://github.com/appaquet/exocore"
version = "0.1.18"

[dependencies]
anyhow = "1.0"
bytes = "1.1"
clap = {version = "3.0.7", features = ["derive", "env"]}
console = "0.15"
dialoguer = "0.9"
dirs-next = "2.0"
exocore-apps-host = {version = "0.1.18", path = "../apps/host"}
exocore-chain = {version = "0.1.18", path = "../chain"}
exocore-core = {version = "0.1.18", path = "../core", features = ["runtime", "logger"]}
exocore-discovery = {version = "0.1.18", path = "../discovery", features = ["server"]}
exocore-protos = {version = "0.1.18", path = "../protos"}
exocore-store = {version = "0.1.18", path = "../store"}
exocore-transport = {version = "0.1.18", path = "../transport", features = ["http-server"]}
futures = "0.3"
indicatif = "0.16"
log = "0.4"
log4rs = "1.0"
rand = "0.8"
reqwest = {version = "0.11", default-features = false, features = ["rustls-tls"]}
tempfile = "3.2"
thiserror = "1.0"
tokio = {version = "1.15", features = ["macros"], default-features = false}
url = "2.2"
zip = "0.5.12"
