[package]
name = "exo"
description = "CLI for Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[dependencies]
exocore-core = { path = "../core", features = ["runtime", "logger"] }
exocore-chain = { path = "../chain" }
exocore-store = { path = "../store" }
exocore-transport = { path = "../transport", features = ["http-server"] }
exocore-discovery = { path = "../discovery", features = ["server"] }
log = "0.4"
clap = "3.0.0-beta.2"
log4rs = "0.13"
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
dirs-next = "2.0"
tempfile = "3.1"
tokio = { version = "0.2", features = ["macros"] }
dialoguer = "0.7"
console = "0.13"
indicatif = "0.15"