[package]
name = "exo"
description = "CLI for Exocore (Distributed applications framework)"
version = "0.1.2"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[dependencies]
exocore-core = { version = "0.1.2", path = "../core", features = ["runtime", "logger"] }
exocore-chain = { version = "0.1.2", path = "../chain" }
exocore-store = { version = "0.1.2", path = "../store" }
exocore-transport = { version = "0.1.2", path = "../transport", features = ["http-server"] }
exocore-discovery = { version = "0.1.2", path = "../discovery", features = ["server"] }
log = "0.4"
clap = "3.0.0-beta.2"
log4rs = "1.0"
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
dirs-next = "2.0"
tempfile = "3.1"
tokio = { version = "0.3", features = ["macros"], default-features = false }
dialoguer = "0.7"
console = "0.14"
indicatif = "0.15"
zip = "0.5"
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls"] }
url = "2.2"
bytes = "1.0"