# Node's keypair and public key
# Use `exo keys generate` to generate node's keys
name: Optional Node Name
public_key: peFdPsQsdqzT2H6cPd3WdU1fGdATDmavh4C17VWWacZTMP
keypair: ae2oiM2PYznyfqEMPraKbpAuA8LWVhPUiUTgdwjvnwbDjnz9W9FAiE9431NtVjfBaX44nPPoNR8Mv6iYcJdqSfp8eZ

# Node's listen addresses
listen_addresses:
  - /ip4/0.0.0.0/tcp/3330
  - /ip4/0.0.0.0/tcp/3341/ws

# Cells that the node is part of
# Use `exo keys generate` to generate cell's keys
cells:
  - location:
      Instance:
        public_key: pe2AgPyBmJNztntK9n4vhLuEYN8P2kRfFXnaZFsiXqWacQ
        keypair: ae55Nfv11ppyFVxCDaYovcxTcaTDaSzSFjiVoiC3VwGARfEuaqGcgoJUdVpqfwKQVDN4rvGKUvt4yqQc6w7it7PCpG
        data_directory: /path/to/data
        name: Optional Cell Name
        nodes:
          - node:
              name: Optional Node Name
              public_key: peFdPsQsdqzT2H6cPd3WdU1fGdATDmavh4C17VWWacZTMP
              addresses:
                - /ip4/127.0.0.1/tcp/3330
                - /ip4/127.0.0.1/tcp/3341/ws

            # Role of the node
            # Chain = 1
            # Index store = 2
            roles:
              - 1
              - 2

          - node:
              name: Some Client Node
              public_key: peHdrwp1ZXicF1v7RQRRC4ursqgE1oM9nuVijCmrf74n7E

        apps:
          - location:
              Directory: ./app
