[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
description = "Distributed applications framework"
edition = "2018"
name = "exocore-discovery"
version = "0.1.2"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["server"]
server = ["hyper", "tokio"]

[dependencies]
anyhow = "1.0"
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
log = "0.4"
rand = "0.7"
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
wasm-timer = "0.2"

# For server
hyper = { version = "0.13", optional = true }
tokio = { version = "0.3", default-features = false, features = ["macros", "time"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio-compat-02 = "0.2"

[[test]]
name = "discovery"
required-features = ["server"]
