[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-discovery"
repository = "https://github.com/appaquet/exocore"
version = "0.1.25"

[features]
default = ["server"]
server = ["hyper", "tokio"]

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
chrono = { version = "0.4.31", features = ["serde"] }
futures = "0.3.29"
log = "0.4.20"
rand = "0.8"
reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls-tls"] }
serde = "1.0.190"
serde_derive = "1.0.190"
serde_json = "1.0.108"
thiserror = "1.0.50"
wasm-timer = "0.2.5"

# For server
hyper = { version = "0.14.27", features = ["full"], optional = true }
tokio = { version = "1.33.0", default-features = false, features = ["macros", "time"], optional = true }

[[test]]
name = "discovery"
required-features = ["server"]
