[package]
name = "exocore-chain"
description = "Distributed applications framework"
version = "0.1.2"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["engine", "directory-chain", "memory-pending"]
tests-utils = ["engine", "tempfile", "directory-chain", "memory-pending", "exocore-core/tests-utils", "exocore-transport/tests-utils"]
engine = []
directory-chain = ["memmap2", "extindex"]
memory-pending = []

[dependencies]
exocore-core = { version = "0.1.2", path = "../core" }
exocore-transport = { version = "0.1.2", path = "../transport", default-features = false }
log = "0.4"
byteorder = "1.3"
thiserror = "1.0"
anyhow = "1.0"
itertools = "0.10"
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"

# For directory chain
memmap2 = { version = "0.2", optional = true }
extindex = { version = "0.4", optional = true }

# For tests
tempfile = { version = "3.2", optional = true }

[dev-dependencies]
exocore-core = { version = "0.1.2", path = "../core", features = ["tests-utils"] }
exocore-transport = { version = "0.1.2", path = "../transport", features = ["tests-utils"] }
tempfile = "3.2"
tokio = { version = "1.0", features = ["macros"], default-features = false }

[[test]]
name = "engine"
required-features = ["tests-utils"]
